source: .
collections_config_override: true
data_config: {}
collections_config:
  pages:
    icon: feed
    disable_add_folder: true
    output: true
    path: ""
    schemas:
      default:
        path: ""
    _enabled_editors:
      - visual
files:
  - label: "Home Page"
    path: index.md
  - label: "About Page"
    path: about.md
  - label: "Contact Page"
    path: contact.md
collection_groups:
  - heading: Pages
    collections:
      - pages
